name: Check Code Formatting

on:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    paths:
      - 'frontend/**'

jobs:
  prettier-check:
    name: Prettier Check (Frontend)
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v5

      # Step 2: Set up Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Step 4: Check formatting with Prettier
      - name: Check Prettier formatting
        working-directory: frontend
        run: |
          npx prettier --check "**/*.{js,ts,svelte,css,scss,md,json}"
